# Probability Distributions 3

In [1]:
import numpy as np
import scipy as sp

## 1 Gaussian Distribution

### 1.1 What is Gaussian Distribution?

#### Definition

A Gaussian Distribution also called as Normal Distribution is a **symmetric**, continuous probability distribution where most data points **cluster around the mean**.

#### Properties

* Normal Distribution is **only** applicable for **Continuous Random variable**.
* Binning the data-points in the distribution using Histogram creates **Bell Curve**.
* In a Bell Curve mean is always present at the center making it **symmetric in nature**.
* Since Normal Distribution is symmetric, Mean, Median and Mode all lie at the center of the distribution at the top.
* **Mean and Standard Deviation** are called as **parameters of a Normal Distribution**.
* We can recreate the entire Normal distribution using its parameters.

### 1.2 Probability Distribution Functions

Normal Distribution is applied on Continuous Random Variable hence we can calculate Probability Density Function (PDF) and Cumulative Density Function (CDF).

#### Probability Density Function

##### How to apply PDF on a Normal Distribution?

Given some range $[x_1,\,x_2]$, the **area under the PDF** (curve) between $x_1$ and $x_2$ gives the probability that the random variable $X$ lies in that range.

$$
\large
\begin{aligned}
P(x_1 \le X \le x_2) = \int_{x_1}^{x_2} f(x)\,dx
\end{aligned}
$$

##### Example

- $P(20.4 < x < 30.6)$ represents probability of a value $x$ falling in between the range $[20.4,\,30.6]$
- Probability Density between the range: $[20.4,\,30.6]$ gives the probability that a random variable $X$ takes a value $x$ between that range.

#### General Equation of PDF

The general form of probability density function for a Normal Distribution:

$$
\large
\begin{aligned}
f(x) = \frac{1}{\sigma\sqrt{2\pi}}\,\mathrm{e}^{-\frac{1}{2}{\Bigl(\frac{x\,-\,\mu}{\sigma}\Bigr)}^2}
\end{aligned}
$$

#### Cumulative Distribution Function

##### How to apply CDF on a Normal Distribution?

Given some limit $x_1$ to a Cumulative Distribution Function, it gives the **probability** that a random variable $X$ takes on a value **less than or equal to** $x_1$.

$$
\large
\begin{aligned}
F(x_1) &= P(X \le x_1) \\[10pt]
       &= \int_{-\infty}^{x_1} f(x)\,dx
\end{aligned}
$$

##### Example

- Cumulative Distribution Function $F_X(51.3)$ on a random variable $X$ gives the probability that $X$ takes on a value less than or equal to 51.3.
- $P(X \le 51.3)$ represents probability of $X$ taking a value less than or equal to 51.3, Its the **cumulative probability up to** 51.3 on the distribution.

### 1.3 Empirical Rule

#### Rule

$$
\large
\begin{aligned}
\text{68 / 95 / 99.7}
\end{aligned}
$$

![Empirical Rule](images/empirical_rule_of_a_normal_distribution.jpg)

#### Explanation

For a given distribution whose mean lie at the center:

1. 68% of data-points lie within 1 standard deviation away from mean.
2. 95% of data-points lie within 2 standard deviation away from mean.
3. 99% of data-points lie within 3 standard deviation away from mean.

In other words, Empirical probability of finding data-points b/w below listed ranges are:

$$
\large
\begin{aligned}
\text{Range}:\bigl[(\mu - 1\sigma),\,(\mu + 1\sigma)\bigr] & \quad & \text{CDF}:P\bigl((\mu - 1\sigma) \le x \le (\mu + 1\sigma)\bigr) = 0.683 \\[5pt]
\text{Range}:\bigl[(\mu - 2\sigma),\,(\mu + 2\sigma)\bigr] & \quad & \text{CDF}:P\bigl((\mu - 2\sigma) \le x \le (\mu + 2\sigma)\bigr) = 0.954 \\[5pt]
\text{Range}:\bigl[(\mu - 3\sigma),\,(\mu + 3\sigma)\bigr] & \quad & \text{CDF}:P\bigl((\mu - 3\sigma) \le x \le (\mu + 3\sigma)\bigr) = 0.997
\end{aligned}
$$

#### Significance of Empirical Rule

1. Mean, Median, Mode all lie at the center does not always prove its a Normal Distribution.
2. Even if a distribution looks like a Bell curve does not always mean its a Normal Distribution.
3. Best way to **identify Normal Distribution** is by using the **Empirical Rule**: 68 / 95 / 99.7

### 1.4 Exercises

#### Exercise #1

The height of people is Gaussian with mean 65 inches and standard deviation 2.5 inches.  
What is the fraction of people whose height is between 60 and 72.5 inches?

##### Solution

In [2]:
# Given,
mu = 65
sigma = 2.5

# Find: P(60 <= x <= 72.5)
# P(x <= 72.5) - P(x <= 60)

In [3]:
# 60 and 72.5 inches is,
mu - (2 * sigma), mu + (3 * sigma)

(60.0, 72.5)

Given range $[60.0, 72.5]$ is exactly between $2\sigma$ (2 standard-deviation) and $3\sigma$ (2 standard-deviation).

In [4]:
# Half of 2SD + Half of 3SD
res = (95.4 / 2) + (99.7 / 2)
round(res, 6)

97.55

#### Exercise #2

The height of people is Gaussian with mean 65 inches and standard deviation 2.5 inches.  
What fraction of people are shorter than 67.5 inches?

##### Solution

In [5]:
# Given,
mu = 65
sigma = 2.5

# Find: P(x <= 67.5)

In [6]:
# 67.5 inches is:
mu + (1 * sigma)

67.5

In [7]:
# Why 0.5?
# Ans: 50% of data is before median
res = 0.5 + (0.683 / 2)
round(res, 6)

0.8415

#### Exercise #3

The height of people is Gaussian with mean 65 inches and standard deviation 2.5 inches.  
What fraction of people are shorter than 70 inches?

##### Solution

In [8]:
# Given,
mu = 65
sigma = 2.5

# Find: P (x <= 70)

In [9]:
# 70 inches is:
mu + (2 * sigma)

70.0

In [10]:
# 50% of data is before median
res = 0.5 + (0.954 / 2)
round(res, 6)

0.977

#### Exercise #4

The height of people is Gaussian with mean 65 inches and standard deviation 2.5 inches.  
What fraction of people are taller than 72.5 inches?

##### Solution

In [11]:
# Given,
mu = 65
sigma = 2.5

# Find: P (x >= 72.5)

In [12]:
# 72.5 inches is:
mu + (3 * sigma)

72.5

In [13]:
# 50% of data is before median
res = 1 - (0.5 + (0.997 / 2))
round(res, 6)

0.0015

## 2 Z-Score

### 2.1 What is Z-Score?

#### Definition

A Z-score (or standard score) measures how many standard deviations $\sigma$ a data point $x$ is above or below the mean $\mu$ of a Normal distribution.

$$
\large
\begin{aligned}
x = \mu + (z \cdot \sigma)
\end{aligned}
$$

#### Integer Z-Scores

##### Sample Z-table for Integer Z-scores

1. Z-table gives the **area to the left of Z-score** i.e., cumulative probability up to the `Z`  value.
2. Below sample Z-table provides probability for integer Z-scores used as multiplier with standard-deviation $\sigma$: $\{\pm\,1\sigma,\,\pm\,2\sigma,\,\pm\,3\sigma\}$.

<div style="display: inline-block">

|   Z |    0.00 |
| --: | ------: |
|  -3 | 0.00135 |
|  -2 | 0.02275 |
|  -1 | 0.15866 |
|  +1 | 0.84134 |
|  +2 | 0.97725 |
|  +3 | 0.99865 |

</div>

Full Z-Table: https://archive.math.arizona.edu/rsims/ma464/standardnormaltable.pdf

##### Probability when using Integer Z-sores

Empirical rule can be derived using Z-table as:

In [14]:
# When Z = 1,
print("Probability between -1SD and +1SD =", 0.84134 - 0.15866)

# When Z = 2,
print("Probability between -2SD and +2SD =", 0.97725 - 0.02275)

# When Z = 3,
print("Probability between -3SD and +3SD =", 0.99865 - 0.00135)

Probability between -1SD and +1SD = 0.68268
Probability between -2SD and +2SD = 0.9544999999999999
Probability between -3SD and +3SD = 0.9973000000000001


$$
\large
\begin{aligned}
\text{When}\quad z = 1:P\bigl((\mu - 1\sigma) \le x \le (\mu + 1\sigma)\bigr) = 0.683 \\[5pt]
\text{When}\quad z = 2:P\bigl((\mu - 2\sigma) \le x \le (\mu + 2\sigma)\bigr) = 0.954 \\[5pt]
\text{When}\quad z = 3:P\bigl((\mu - 3\sigma) \le x \le (\mu + 3\sigma)\bigr) = 0.997 \\[5pt]
\end{aligned}
$$

#### Formula

Formula to calculate Z-Score (integer or non-integer multiplier) using mean $\mu$ and standard-deviation $\sigma$

$$
\large
\begin{aligned}
\text{Z-Score} = \frac{x - \mu}{\sigma}
\end{aligned}
$$

Where $x$ is some value of a random variable $X$

#### Properties

1. Z-score can be zero, positive or negative.  
1. A **zero Z-score** indicates that the data-point is **mean itself**.  
1. A **positive Z-score** indicates that the data-point lies on the **right side of mean**.  
1. A **negative Z-score** indicates that the data-point lies on the **left side of mean**.
1. A data-point with a Z-score beyond $\pm\,2.5$ or $\pm\,3$ is typically considered an unusual value or a **statistical outlier**.

### 2.2 Exercises

#### Exercise #1

The height of people is Gaussian with mean 65 inches and standard deviation 2.5 inches.  
What fraction of people are shorter than 69.1 inches?

##### Solution

In [15]:
mu = 65
sigma = 2.5

# Find: P(x <= 69.1)
x = 69.1

In [16]:
z_score = (x - mu) / sigma
round(z_score, 6)

1.64

In [17]:
sp.stats.norm.cdf(z_score).round(6).item()

0.949497

#### Exercise #2

The height of people is Gaussian with mean 65 inches and standard deviation 2.5 inches.  
What fraction of people are shorter than 67.5 inches?

##### Solution

In [18]:
mu = 65
sigma = 2.5

# Find: P(x < 67.5)
x = 67.5

In [19]:
z_score = (x - mu) / sigma
z_score

1.0

In [20]:
sp.stats.norm.cdf(z_score).round(6).item()

0.841345

#### Exercise #3

Balls produced by the manufacturer have a mean diameter of 50 mm and std dev 2 mm.  
What fraction of balls have a diameter smaller than 53 mm?

##### Solution

In [21]:
mu = 50
sigma = 2

# Find: P(x < 53)
x = 53

In [22]:
z_score = (x - mu) / sigma
z_score

1.5

In [23]:
sp.stats.norm.cdf(z_score).round(6).item()

0.933193

## 3 Percent Point Function `ppf`

### 3.1 What is Percent Point Function?

The percent point function (PPF) is the inverse of the cumulative distribution function (CDF).

#### `cdf` vs `ppf`

* Given percentile, use `ppf()` to get Z-Score from Percentile.
* Pass given probability to `sp.stats.norm.ppf()` function and it returns Z-Score.
* Given Z-score, use `cdf()` to get Percentile from Z-Score.
* Pass given Z-score to `sp.stats.norm.cdf()` function and it returns probability.

In [24]:
sp.stats.norm.cdf(sp.stats.norm.ppf(0.7))

np.float64(0.7)

### 3.2 Exercises

#### Exercise #1

The height of people is Gaussian Distribution with mean height of 65 inches and standard deviation of 2.5 inches.  
One person says "96% of people are shorter than me". What is that person's height?

##### Solution

In [25]:
mu = 65
sigma = 2.5
prob = 0.96
# Find x (height of the person).

In [26]:
z_score = sp.stats.norm.ppf(prob).round(6)
print(f"z-core for the probability of {prob} is {z_score}")

z-core for the probability of 0.96 is 1.750686


In [27]:
x = mu + (z_score * sigma)
print(f"Person's Height is {round(x, 2)} inches.")

Person's Height is 69.38 inches.


#### Exercise #2

Skaters take a mean of 7.42 seconds and std dev of 0.34 seconds for 500 meters.  
What should his speed be such that he is faster than 95% of his competitors?

##### Solution

In [28]:
mu = 7.42
sigma = 0.34
distance = 500
# Find speed such that P(time < x) <= 5%.
prob = round(1 - 0.95, 2)  # Top 5%

In [29]:
z_score = sp.stats.norm.ppf(prob).round(6).item()
print(f"z-score value for probability {prob} is {z_score}.")

z-score value for probability 0.05 is -1.644854.


In [30]:
time = mu + (z_score * sigma)
time = round(time, 2)
print(f"Time at z-score {z_score} is {time}")

Time at z-score -1.644854 is 6.86


In [31]:
speed = distance / time
speed = round(speed, 2)
print(f"Speed must be {speed} to be in top 5%")

Speed must be 72.89 to be in top 5%


#### Exercise #3

A retail outlet sells around 1000 toothpastes a week, with standard deviation = 200.  
If we have 1300 stock units as our inventory, then 

1. What is the probability you'd need to replenish stocks?
2. How much inventory should you have, such that there is only 3% chance of running out of stock mid-week?

##### Solution

PART 1:

In [32]:
mu = 1000
sigma = 200

# We have to replenish stock if sales goes > 1300.
# Hence find: P(x > 1300)
# P(x > 1300) = 1 - P(x < 1300)
x = 1300

In [33]:
z_score = (x - mu) / sigma
z_score

1.5

In [34]:
prob_x_gt_1300 = 1 - sp.stats.norm.cdf(z_score)
print(round(prob_x_gt_1300, 6))

0.066807


PART 2:

In [35]:
# Probability that you are 97% in stock:
prob = 1 - 0.03

In [36]:
z_score = sp.stats.norm.ppf(prob).round(2)
x = mu + (z_score * sigma)
print(x)

1376.0


## 4 Standard Normal Distribution

### 4.1 What is Standard Normal Distribution?

#### Definition

Normal Distribution with mean zero and standard deviation one is called as Standard Normal Distribution.

$$
\large
\begin{aligned}
Z \sim N(\mu = 0,\,\sigma = 1)
\end{aligned}
$$

#### General Equation of PDF

The general form of probability density function for a Standard Normal Distribution:

$$
\large
\begin{aligned}
f(x) = \frac{1}{\sqrt{2\pi}}\,\mathrm{e}^{-\frac{1}{2}\,x^2}
\end{aligned}
$$

#### Properties

1. We can take any Normal Distribution and convert it to The Standard Normal Distribution, using Standardization.
2. In all the above CDF calculations the given distribution was scaled down to Standard Normal Distribution `Z` using below formula:

$$
\large
\begin{aligned}
Z = \frac{x - \mu}{\sigma}
\end{aligned}
$$

## 5 Appendix

### 5.1 CDF Calculation

#### Continuous Distribution

##### Case 1

$$
\large
\begin{aligned}
\text{To find}:\,& P(x < n) \\[3pt]
                 & = \text{cdf}(n)
\end{aligned}
$$

##### Case 2

$$
\large
\begin{aligned}
\text{To find}:\,& P(X > n) \\[3pt]
                 & = 1 - P(x < n) \\[3pt]
                 & = 1 - \text{cdf}(n)
\end{aligned}
$$

##### Case 3

$$
\large
\begin{aligned}
\text{To find}:\,& P(a < x < b) \\[3pt]
                 & = P(x < b) - P(x < a) \\[3pt]
                 & = \text{cdf}(b) - \text{cdf}(a)
\end{aligned}
$$